name: bookbinder

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Python environment
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
          architecture: x64

      - name: Install system dependencies
        run: |
          sudo apt update
          sudo apt install -y texlive-full

      - name: Install Python dependencies
        run: |
          python -m pip install -r requirements.txt

      - name: Generate documents
        run: |
          make

      - name: Upload artifacts
        uses: actions/upload-artifact@v2-preview
        with:
          name: resume
          path: build/*
